### ISSUE TITLE
Looking forward for your 4th article in codeproject

### ISSUE THREAD

**Issue by EruditePig** [jll63/yomm11#4]
Thank you for your excellent library , I am very interested in multiple dispatch and type erasure. I am reading your code and try to use it with type erasure container, however, the code is difficult, so i hope the 4th and final article can help me .

Again, Thank you  for your library and effort!

**Comment by jll63** [comment]
Aaah, I am not going to write it, sorry. I am working on a new version that will profit from some of the ideas I got during the port to dlang. It will be simpler and hopefully will support method overload. Wiritng article #4 would be a waste of time and effort. I should edit the articles to remove mention of article 4 though.
If you can describe your situation more precisely I may be able to help you figure it out, if you haven't already.
